version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
      - run:
          name: Run Code Coverage (JaCoCo)
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: app/build/reports/jacoco
          destination: jacoco-report
      - run:
          name: Run Code Style Check (ktlint)
          command: ./gradlew ktlintCheck
      - store_artifacts:
          path: app/build/reports/ktlint
          destination: ktlint-report
      - run:
          name: Run Dependency Vulnerability Scan (OWASP)
          command: ./gradlew dependencyCheckAnalyze
      - store_artifacts:
          path: build/reports/dependency-check-report.html
          destination: dependency-vulnerability-report
